version: '3.3'

services:
  jupyter:
    image: jupyter/datascience-notebook
    ports:
      - 80:8888
    volumes:
      - workspace:/home/jovyan/work
    environment:
      - GRANT_SUDO=yes

volumes:
  workspace:

